-- BOARD TABLE 생성 --
CREATE TABLE BOARD( 
	IDX INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(100) NOT NULL,
	CONTENTS VARCHAR(2000) NOT NULL,
	WRITER VARCHAR(30) NOT NULL,
	INDATE DATETIME DEFAULT NOW(),
	COUNT INT DEFAULT 0,
	PRIMARY KEY(IDX)
);

INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('여기가 제목임', '여기가 내용임', '작성자 이름임');

INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('인장주작은 뭐야', 'c', 'ME');

INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('CI', 'ㅈㄱㄴ', 'MONKEY');

INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('BAL', 'ㅈㄱㄴ', 'MONKEY');

INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('NYENN', 'ㅈㄱㄴ', 'MONKEY');

commit;

select * from BOARD;
